version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.40.6
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:9.3.1
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000" # access grafana url
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug